import os
import json

APPLE_CONNECT_PRIVATE_KEY = os.getenv("APPLE_CONNECT_PRIVATE_KEY")
APPLE_CONNECT_ISSUER_ID = os.getenv("APPLE_CONNECT_ISSUER_ID")
APPLE_CONNECT_APP_ID = os.getenv("APPLE_CONNECT_APP_ID")
APPLE_CONNECT_KEY_ID = os.getenv("APPLE_CONNECT_KEY_ID")
APPLE_CONNECT_VENDOR_NUMBER = os.getenv("APPLE_CONNECT_VENDOR_NUMBER")
APPLE_BASE_URL = os.getenv("APPLE_BASE_URL")

SNOWFLAKE_ACCOUNT_NAME = os.getenv("SNOWFLAKE_ACCOUNT_NAME")
SNOWFLAKE_USER_NAME = os.getenv("SNOWFLAKE_USER_NAME")
SNOWFLAKE_PASSWORD = os.getenv("SNOWFLAKE_PASSWORD")
SNOWFLAKE_DATABASE = os.getenv("SNOWFLAKE_DATABASE")
SNOWFLAKE_SCHEMA_TEMP = os.getenv("SNOWFLAKE_SCHEMA_TEMP")
SNOWFLAKE_WAREHOUSE = os.getenv("SNOWFLAKE_WAREHOUSE")
SNOWFLAKE_TEMP_TABLE = os.getenv("SNOWFLAKE_TEMP_TABLE")
SNOWFLAKE_PRD_TABLE = os.getenv("SNOWFLAKE_PRD_TABLE")
