CREATE OR REPLACE TABLE {TEMP_TABLE}
            (
                Provider STRING,
                "Provider Country" STRING,
                SKU STRING,
                Developer STRING,
                Title STRING,
                Version STRING,
                "Product Type Identifier" STRING,
                Units INTEGER,
                "Developer Proceeds" FLOAT,
                "Begin Date" STRING,
                "End Date" STRING,
                "Customer Currency" STRING,
                "Country Code" STRING,
                "Currency of Proceeds" STRING,
                "Apple Identifier" INTEGER,
                "Customer Price" FLOAT,
                "Promo Code" STRING,
                "Parent Identifier" STRING,
                Subscription STRING,
                Period STRING,
                Category STRING,
                CMB STRING,
                Device STRING,
                "Supported Platforms" STRING,
                "Proceeds Reason" STRING,
                "Preserved Pricing" STRING,
                Client STRING,
                "Order Type" STRING);